### ISSUE TITLE
AKS deployment for DZ-team

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [frmscoe/helm#19]
Assist Nadjib with AKS deployment

**Comment by vorsterk** [comment]
## Task Checklist

- [x] Kubernetes token - DONE
- [x] Changed and created a secret called `frmpullsecret` that has Docker config - DONE
- [x] Use the server API endpoint from your kube config file - DONE
- [x] Change repo names to include the `rel-1-0-0` - DONE
- [x] Specific ingress to note for TMS - DONE
- [x] Add Elasticsearch cert stuff for Lumberjack/Event sidecar - DONE
- [x] Remove ArangoDB deployment jobs `<assignedNode>jenkins-agent</assignedNode>` - DONE
- [x] TADP - Jenkins database URLs and passwords need to be populated since splitdb changes - DONE
- [x] Add new variable for `ArangoEvaluationURL` and `ArangoEvaluationPassword` as well - DONE
- [x] `ENV SERVER_URL=0.0.0.0:4222` - Change Jenkins job to in TADP - DONE
  - `sed -i "s|ENV SERVER_URL=0.0.0.0:4222|ENV SERVER_URL=${NATS_SERVER_URL}|g" Dockerfile`
- [x] CMS - Change the `readpackage` line - DONE
  - `sed -i "s/\${GH_TOKEN}/${READ_GH_TOKEN}/g" .npmrc`
- [x] Rename FRMS to Tazama - DONE

**Comment by vorsterk** [comment]
Changes mad eon this PR - https://github.com/frmscoe/AKS-helm/pull/21

**Comment by vorsterk** [comment]
Task closed , Scott is assisting them now . The new updates to the AKS stuff has been added and is up to date .
